using Microsoft.AspNetCore.Mvc;
using SimpleApi.Models;

namespace SimpleApi.Controllers
{
    [ApiController]
        [Route("api/[controller]")]
            public class TodoController : ControllerBase
                {
                        private static List<TodoItem> _todoItems = new List<TodoItem>
                                {
                                            new TodoItem { Id = 1, Title = "Buy groceries", Description = "Milk, eggs, bread", IsCompleted = false },
                                                        new TodoItem { Id = 2, Title = "Read a book", Description = "Finish reading C# in Depth", IsCompleted = true }
                                                                };

                                                                        private static int _nextId = 3;

                                                                                // GET: api/todo
                                                                                        [HttpGet]
                                                                                                public ActionResult<IEnumerable<TodoItem>> GetAll()
                                                                                                        {
                                                                                                                    return Ok(_todoItems);
                                                                                                                            }
                                                                                                                            
                                                                                                                                    // GET: api/todo/1
                                                                                                                                            [HttpGet("{id}")]
                                                                                                                                                    public ActionResult<TodoItem> GetById(int id)
                                                                                                                                                            {
                                                                                                                                                                        var item = _todoItems.FirstOrDefault(t => t.Id == id);
                                                                                                                                                                                    if (item == null)
                                                                                                                                                                                                    return NotFound();
                                                                                                                                                                                                                return Ok(item);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                // POST: api/todo
                                                                                                                                                                                                                                        [HttpPost]
                                                                                                                                                                                                                                                public ActionResult<TodoItem> Create([FromBody] TodoItem newItem)
                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                    newItem.Id = _nextId++;
                                                                                                                                                                                                                                                                                newItem.CreatedAt = DateTime.UtcNow;
                                                                                                                                                                                                                                                                                            _todoItems.Add(newItem);
                                                                                                                                                                                                                                                                                                        return CreatedAtAction(nameof(GetById), new { id = newItem.Id }, newItem);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        // PUT: api/todo/1
                                                                                                                                                                                                                                                                                                                                [HttpPut("{id}")]
                                                                                                                                                                                                                                                                                                                                        public ActionResult<TodoItem> Update(int id, [FromBody] TodoItem updatedItem)
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                            var item = _todoItems.FirstOrDefault(t => t.Id == id);
                                                                                                                                                                                                                                                                                                                                                                        if (item == null)
                                                                                                                                                                                                                                                                                                                                                                                        return NotFound();
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                    item.Title = updatedItem.Title;
                                                                                                                                                                                                                                                                                                                                                                                                                item.Description = updatedItem.Description;
                                                                                                                                                                                                                                                                                                                                                                                                                            item.IsCompleted = updatedItem.IsCompleted;
                                                                                                                                                                                                                                                                                                                                                                                                                                        return Ok(item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // DELETE: api/todo/1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                [HttpDelete("{id}")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public ActionResult Delete(int id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var item = _todoItems.FirstOrDefault(t => t.Id == id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (item == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NotFound();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _todoItems.Remove(item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return NoContent();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
